name: "CI"

on:
  pull_request:
    branches:
      - develop
      - master
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
          git clone -b master https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          php phpcs.phar --config-set installed_paths wpcs
          php phpcs.phar -i

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: phpcs.ruleset.xml